name: Build APK on Demand

on:
  workflow_dispatch:

jobs:
  apk:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set execution flag for gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Build Tools
        run: |
          sdkmanager "build-tools;36.0.0"
          sdkmanager "build-tools;29.0.3"

      - name: Build APK
        run: bash ./gradlew :androidApp:assembleFossRelease --stacktrace

      - name: Find APK
        run: find androidApp -name "*.apk" 2>/dev/null

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kai-custom-apk
          path: androidApp/build/outputs/apk/foss/release/androidApp-foss-release-unsigned.apk
